import { readFileSync } from "fs";
import { client } from "./index.js";

async function getTopPost(guildName) {
  return await client.guilds.get(guildName).fetchPosts({ sort: "top", page: 1, t: "day", limit: 2, timeframe: [] }).catch(async e => {
    console.log("Failed to get " + guildName + "... Retrying");
    console.log(e);
    return await getTopPost(guildName);
  });
}

export default async function guildDetails() {
  let guilds = [];
  readFileSync("guildlist.txt", "utf-8")
    .split(/\r?\n/)
    .forEach((line) => {
      if (!line.startsWith("#")) {
        guilds.push(line.split("+")[1]);
      }
    });

  let toplist = [];

  for (let i = 0; i < guilds.length; i++) {
    let topTwo = await getTopPost(guilds[i]);
    toplist.push(...topTwo);
  }

  toplist = toplist.sort((a, b) => {
    return b.votes.score - a.votes.score;
  });

  let postContent = `
  Votes | URL
  --- | ---
  `
  toplist.forEach(topPost => {
    postContent += `\n${topPost.votes.score} | ${topPost.full_link}`;
  });
  postContent += "\n\n^(This post was generated by a bot using [ruqqus-js](https://www.npmjs.com/package/ruqqus-js))"

  console.log(postContent);
  console.log(
    client.guilds.get("test").post("Today's Non-Political Front Page", postContent)
  );
}