import { readFileSync } from "fs";
import { client } from "./index.js";

async function getTopPost(guildName) {
  return await client.guilds.get(guildName).fetchPosts({ sort: "top", page: 1, filter: "day", limit: 2, timeframe: [Date.now() - 1000*60*60*24, Date.now()] }).catch(async e => {
    console.log("Failed to get " + guildName + "... Retrying");
    console.log(e);
    return await getTopPost(guildName);
  });
}

export default async function guildDetails() {
  let guilds = [];
  readFileSync("guildlist.txt", "utf-8")
    .split(/\r?\n/)
    .forEach((line) => {
      if (!line.startsWith("#")) {
        guilds.push(line.split("+")[1]);
      }
    });

  let toplist = [];

  for (let i = 0; i < guilds.length; i++) {
    let topTwo = await getTopPost(guilds[i]);
    toplist.push(...topTwo);
    // console.log(topTwo[0]);
  }

  toplist = toplist.sort((a, b) => {
    return b.votes.score - a.votes.score;
  });

  let postContent = `Votes | Link\n--- | ---`
  toplist.forEach(topPost => {
    postContent += `\n${topPost.votes.score} | [${topPost.content.title}](${topPost.full_link})`;
  });
  postContent += "\n\n*This post was generated by a bot using [ruqqus-js](https://www.npmjs.com/package/ruqqus-js)*"

  postContent.split("+").join(""); //Remove +s because they break formatting..

  console.log(postContent);
  //client.guilds.get("KeepingTheBalance").post("Today's Non-Political Front Page", postContent);
}